version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wedding_planner_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/wedding_planner_development
    volumes:
      - .:/app
    command: >
      bash -c "
        bundle exec rails db:create 2>/dev/null || true &&
        RAILS_ENV=test bundle exec rails db:create 2>/dev/null || true &&
        bundle exec rails db:migrate &&
        RAILS_ENV=test bundle exec rails db:migrate &&
        bundle exec rails server -b 0.0.0.0 -p 4000
      "

volumes:
  postgres_data: