default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wedding_planner_development
  username: <%= ENV.fetch("DATABASE_USERNAME") { "" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

test:
  <<: *default
  database: wedding_planner_test
  username: <%= ENV.fetch("DATABASE_USERNAME") { "" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>

production:
  <<: *default
  database: wedding_planner_production
  username: wedding_planner
  password: <%= ENV["WEDDING_PLANNER_DATABASE_PASSWORD"] %>
